### ISSUE TITLE
error: failed to get bookings

### ISSUE THREAD

**Issue by jonaswagner** [churchtools/ctnodedemo#1]
I was trying to run demo.js with the (slightly anonymized) credentials below:

    host: 'https://zollhaus.churchtools.de',
    user: 'myEmail@whatever.com',
    password: 'IAMAPASSWORD'

This is what I get:

debug: {"timestamp":"2017-05-05T14:28:56.615Z","id":0,"module":"lib/ctaccessor","uuid":"74AB9450-438F-4476-93E6-3EC251539EB1","level":"debug","message":"Calling CT API login/ajax \"login\" ..."}
debug: {"timestamp":"2017-05-05T14:28:57.214Z","id":1,"module":"lib/ctaccessor","uuid":"4FDE9C12-A090-49ED-993C-D723D5EB2CDE","level":"debug","message":"Response from CT call login/ajax \"login\" : 200"}
debug: {"timestamp":"2017-05-05T14:28:57.215Z","id":2,"module":"lib/ctaccessor","uuid":"B24CED24-F24A-478A-B709-1473749A9EF1","level":"debug","message":"Found new cookie: ChurchTools_ct_zollhaus=HERE_WAS_A_VALID_TOKEN"}
error: {"timestamp":"2017-05-05T14:28:57.218Z","id":3,"module":"demo","uuid":"06E775F1-4BFD-43F1-ABBD-C5836CA71D1F","level":"error","message":"failed to get bookings.","metadata":{"err":{"message":"Call to CT, login/ajax \"login\", failed: undefined"}}}

Can you help me?

**Comment by hubermat** [comment]
Most likely you had the user's mail address or the password wrong in the credentials.js 
Just tested with again and it works fine. If I change the mail address to a bad one, I get the same results like you. 
You could add a line
`console.dir(result);`
before or after ctaccessor.js:76 to display the result with the error message. With a bad/unknown mail address this is
`{ status: 'fail',
  data: 'Die E-Mail-Adresse ist nicht bekannt!' }
`

**Comment by jonaswagner** [comment]
I tried again. It fails with the following message: { status: 'fail', data: 'Das Passwort ist nicht korrekt.' }. 

I double checked my password and even changed it but it won't connect...

Do I have to transmit a hash of my password or something else?
Is there any problem with special characters?

**Comment by hubermat** [comment]
Yes, following characters in password make problems with the API: `<>"&`
All other special characters should work fine. 
You could start with a fairly simple password without special characters to check basic functionality. Then change to password to a stronger one.

**Comment by djschilling** [comment]
@jonaswagner Can the issue be closed? Were you able to correctly use the api?

**Comment by jonaswagner** [comment]
I was able to correctly use it
