### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by schnells** [churchtools/ctnodedemo#2]
Call to CT, login/ajax \"login\", failed: **undefined**

What does undefined mean? Appended a log from the output of _node demo.js_

[log.txt](https://github.com/churchtools/ctnodedemo/files/1458155/log.txt)

**Comment by hubermat** [comment]
I just enhanced the error output for this case. Please update (git pull) and try again. The error message should now be more descriptive. Please post the log again, then.

**Comment by schnells** [comment]
Now its working, it loggs correctly email not found, or password wrong or its working!
